### ISSUE TITLE
Switching gearsets doesnt toggle visor state.

### ISSUE THREAD

**Issue by Avalon304** [Ottermandias/AutoVisor#1]
When switching to a gear sets the visor state of head gear doesnt update, especially noticable when switching between gear sets where the head gear visors in opposite states. (For instance the Machinist's Goggles and Ironworks Optics of Healing cover the eye in opposite states (goggles with Visor On, Optics with visor off)). Happy to record a video of what happens if it would help.

**Comment by Ottermandias** [comment]
Problem is probably that the gear set stores the state and toggles, but does so later than my toggle, but my toggle waits until the visor state it supposedly toggled is reached (which is then basically infinite).
I implemented delay on job change and a reset of the expected visor state after the same delay. You can set this delay (in frames) yourself, but I'd just keep it at 30 frames. Go lower if it works well. Do not go too low.

I pushed this change to [T] but will not push it to the Dalamud repo yet because of the other potential issue, so it would be great if you could try it out (either compile it manually or add the https://raw.githubusercontent.com/Ottermandias/AutoVisor/master/repo.json to your custom repos and install [T].

**Comment by Avalon304** [comment]
Installed the testing version just now and the delay does help. Leaving it at 30 frames occasionally cause the visor to toggle on and off a couple of times before getting to the correct position, but I set it to 60 frames and it appears to work properly, just toggling the visor to the correct position after switching gear sets.

**Comment by Ottermandias** [comment]
Oh yeah, frames depends on your framerate, obviously. During development mine is pretty low because for some reason every imgui window with its own viewport (i.e. outside the game) shares the frame rate with the game, i.e. 3 imgui windows outside goes to 120/3 = 40 fps. :D
If the delay when changing job doesn't bother you, higher number is more stable, I guess.
